#!/bin/bash

# Delete only old AutoUpdate assets for the source/device currently being built.
# Prefixes are generated by common/upgrade.sh in $GITHUB_WORKSPACE/del_assets.
function delete_assets_by_prefix() {
    local prefix="$1"
    local api_response asset_rows asset_id asset_name

    [[ -n "${prefix}" ]] || return 0

    api_response="$(curl -fsSL \
        -H "Authorization: Bearer ${REPO_TOKEN}" \
        -H "Accept: application/vnd.github+json" \
        "https://api.github.com/repos/${GIT_REPOSITORY}/releases/tags/${UPDATE_TAG}" 2>/dev/null || true)"

    if [[ -z "${api_response}" ]] || [[ "$(jq -r '.message? // empty' <<< "${api_response}" 2>/dev/null)" == "Not Found" ]]; then
        echo "AutoUpdate Release 尚不存在，无需清理: ${UPDATE_TAG}"
        return 0
    fi

    asset_rows="$(jq -r --arg prefix "${prefix}" \
        '.assets[]? | select(.name | startswith($prefix)) | "\(.id)\t\(.name)"' \
        <<< "${api_response}" 2>/dev/null)"

    [[ -n "${asset_rows}" ]] || {
        echo "没有需要清理的旧固件: ${prefix}*"
        return 0
    }

    while IFS=$'\t' read -r asset_id asset_name; do
        [[ -n "${asset_id}" ]] || continue
        echo "删除旧的在线更新固件: ${asset_name} (ID: ${asset_id})"
        curl -fsSL -X DELETE \
            -H "Authorization: Bearer ${REPO_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${GIT_REPOSITORY}/releases/assets/${asset_id}" \
            >/dev/null || {
                echo "警告: 删除失败 ${asset_name}"
                return 1
            }
    done <<< "${asset_rows}"
}

delete_assets_by_prefix "${DELETE_PREFIX_1}"
delete_assets_by_prefix "${DELETE_PREFIX_2}"
